sonar.projectKey=Felipe0822_SistemaEnviosPruebasUnitarias
sonar.organization=felipe0822
sonar.sources=src
sonar.tests=tests
sonar.typescript.lcov.reportPaths=coverage/lcov.info
sonar.sourceEncoding=UTF-8